# Generated by Django 3.1.4 on 2021-01-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_post_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
